/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import config.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author chand
 */
public class FrmDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDashboard.class.getName());

    /**
     * Creates new form FrmDashboard
     */
    public FrmDashboard() {
       initComponents();
        tampilTanggal();
        loadDashboard();
        eventMenu();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

 private void tampilTanggal() {
        SimpleDateFormat format = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        lbltanggal.setText(format.format(new Date()));
    }

    private void eventMenu() {

    btnObat.setCursor(
            new java.awt.Cursor(
                    java.awt.Cursor.HAND_CURSOR));

    btnPelanggan.setCursor(
            new java.awt.Cursor(
                    java.awt.Cursor.HAND_CURSOR));

    btnSupplier.setCursor(
            new java.awt.Cursor(
                    java.awt.Cursor.HAND_CURSOR));
}

private void loadDashboard() {

    try (Connection conn = Koneksi.getConnection();
         Statement st = conn.createStatement()) {

        ResultSet rs;

        // Total Obat
        rs = st.executeQuery(
                "SELECT COUNT(*) total FROM obat");
        if (rs.next()) {
            lbljumlahobat.setText(
                    rs.getString("total"));
        }

        // Total Pelanggan
        rs = st.executeQuery(
                "SELECT COUNT(*) total FROM pelanggan");
        if (rs.next()) {
            lbljumlahpelanggan.setText(
                    rs.getString("total"));
        }

        // Total Supplier
        rs = st.executeQuery(
        "SELECT COUNT(*) total FROM supplier");

if (rs.next()) {
    lbljumlahsupplier.setText(
            rs.getString("total"));
}

        // Total Transaksi
rs = st.executeQuery(
        "SELECT COUNT(*) total FROM penjualan");

if (rs.next()) {
    lbljumlahtransaksi.setText(
            rs.getString("total"));
}

rs = st.executeQuery(
    "SELECT IFNULL(SUM(subtotal),0) total FROM penjualan");

if (rs.next()) {
    lbljumlahpendapatan.setText(
    "Rp " + rs.getString("total")); 
}

rs = st.executeQuery(
    "SELECT COUNT(*) total FROM obat WHERE stok <= 5");

if (rs.next()) {
    jLabel3.setText(
        rs.getString("total"));
}
        
        

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal memuat dashboard : "
                        + e.getMessage());

    }
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnPenjualan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbltanggal = new javax.swing.JLabel();
        card_obat = new javax.swing.JPanel();
        lbljumlahobat = new javax.swing.JLabel();
        card_pelanggan = new javax.swing.JPanel();
        lbljumlahpelanggan = new javax.swing.JLabel();
        card_supplier = new javax.swing.JPanel();
        lbljumlahsupplier = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        card_transaksi = new javax.swing.JPanel();
        lbljumlahtransaksi = new javax.swing.JLabel();
        lblJumlahTransaksi = new javax.swing.JLabel();
        lblTotalPendapatan = new javax.swing.JPanel();
        lbljumlahpendapatan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblstokmenipis = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jLabel10.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        jPanel1.setToolTipText("");

        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24.png"))); // NOI18N
        dashboard.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pelanggan_24.png"))); // NOI18N
        btnPelanggan.setText("Pelanggan");
        btnPelanggan.addActionListener(this::btnPelangganActionPerformed);

        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/obat_24.png"))); // NOI18N
        btnObat.setText("Obat");
        btnObat.addActionListener(this::btnObatActionPerformed);

        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supplier_24.png"))); // NOI18N
        btnSupplier.setText("Supplier");
        btnSupplier.addActionListener(this::btnSupplierActionPerformed);

        btnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/store_24.png"))); // NOI18N
        btnPenjualan.setText("Penjualan");
        btnPenjualan.addActionListener(this::btnPenjualanActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnObat)
                .addGap(12, 12, 12)
                .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPenjualan)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apotek_24.png"))); // NOI18N
        jLabel5.setText("Apotek Kita");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(17, 17, 17))
        );

        lbltanggal.setText("tgl");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltanggal)
                .addGap(38, 38, 38))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbltanggal)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        card_obat.setBackground(new java.awt.Color(0, 255, 255));
        card_obat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbljumlahobat.setText("0");

        javax.swing.GroupLayout card_obatLayout = new javax.swing.GroupLayout(card_obat);
        card_obat.setLayout(card_obatLayout);
        card_obatLayout.setHorizontalGroup(
            card_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_obatLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbljumlahobat)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        card_obatLayout.setVerticalGroup(
            card_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_obatLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbljumlahobat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card_pelanggan.setBackground(new java.awt.Color(255, 51, 51));
        card_pelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbljumlahpelanggan.setText("0");

        javax.swing.GroupLayout card_pelangganLayout = new javax.swing.GroupLayout(card_pelanggan);
        card_pelanggan.setLayout(card_pelangganLayout);
        card_pelangganLayout.setHorizontalGroup(
            card_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_pelangganLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbljumlahpelanggan)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        card_pelangganLayout.setVerticalGroup(
            card_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_pelangganLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbljumlahpelanggan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card_supplier.setBackground(new java.awt.Color(102, 255, 102));
        card_supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbljumlahsupplier.setText("0");

        javax.swing.GroupLayout card_supplierLayout = new javax.swing.GroupLayout(card_supplier);
        card_supplier.setLayout(card_supplierLayout);
        card_supplierLayout.setHorizontalGroup(
            card_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_supplierLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbljumlahsupplier)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        card_supplierLayout.setVerticalGroup(
            card_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_supplierLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbljumlahsupplier)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel6.setText("Jumlah Obat");

        jLabel7.setText("Jumlah Pelanggan");

        jLabel8.setText("Jumlah Supplier");

        card_transaksi.setBackground(new java.awt.Color(102, 255, 102));
        card_transaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbljumlahtransaksi.setText("0");

        javax.swing.GroupLayout card_transaksiLayout = new javax.swing.GroupLayout(card_transaksi);
        card_transaksi.setLayout(card_transaksiLayout);
        card_transaksiLayout.setHorizontalGroup(
            card_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_transaksiLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbljumlahtransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_transaksiLayout.setVerticalGroup(
            card_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_transaksiLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbljumlahtransaksi)
                .addGap(17, 17, 17))
        );

        lblJumlahTransaksi.setText("Jumlah Transaksi");

        lblTotalPendapatan.setBackground(new java.awt.Color(102, 255, 204));

        lbljumlahpendapatan.setText("0");

        javax.swing.GroupLayout lblTotalPendapatanLayout = new javax.swing.GroupLayout(lblTotalPendapatan);
        lblTotalPendapatan.setLayout(lblTotalPendapatanLayout);
        lblTotalPendapatanLayout.setHorizontalGroup(
            lblTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTotalPendapatanLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbljumlahpendapatan)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        lblTotalPendapatanLayout.setVerticalGroup(
            lblTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTotalPendapatanLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbljumlahpendapatan)
                .addGap(19, 19, 19))
        );

        jLabel1.setText("Total Pendapatan");

        lblstokmenipis.setBackground(new java.awt.Color(255, 255, 51));

        jLabel3.setText("0");

        javax.swing.GroupLayout lblstokmenipisLayout = new javax.swing.GroupLayout(lblstokmenipis);
        lblstokmenipis.setLayout(lblstokmenipisLayout);
        lblstokmenipisLayout.setHorizontalGroup(
            lblstokmenipisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblstokmenipisLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        lblstokmenipisLayout.setVerticalGroup(
            lblstokmenipisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblstokmenipisLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        jLabel2.setText("Stok Habis");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setText("Selamat Datang di Apotek Kita!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(card_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(10, 10, 10)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(card_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(card_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel2))
                                    .addComponent(lblstokmenipis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(lblJumlahTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(card_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(132, 132, 132))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(card_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(card_obat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(card_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblJumlahTransaksi)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstokmenipis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(card_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
       FrmObat form = new FrmObat();
    form.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        
    FrmPelanggan form =
            new FrmPelanggan();

    form.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        // TODO add your handling code here:
        FrmSupplier form =
        new FrmSupplier();

        form.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        // TODO add your handling code here:
         FrmPenjualan form =
        new FrmPenjualan();

        form.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JPanel card_obat;
    private javax.swing.JPanel card_pelanggan;
    private javax.swing.JPanel card_supplier;
    private javax.swing.JPanel card_transaksi;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblJumlahTransaksi;
    private javax.swing.JPanel lblTotalPendapatan;
    private javax.swing.JLabel lbljumlahobat;
    private javax.swing.JLabel lbljumlahpelanggan;
    private javax.swing.JLabel lbljumlahpendapatan;
    private javax.swing.JLabel lbljumlahsupplier;
    private javax.swing.JLabel lbljumlahtransaksi;
    private javax.swing.JPanel lblstokmenipis;
    private javax.swing.JLabel lbltanggal;
    // End of variables declaration//GEN-END:variables
}
