/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import config.Koneksi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FrmPelanggan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPelanggan.class.getName());

    /**
     * Creates new form FrmPelanggan
     */
    public FrmPelanggan() {
      initComponents();
    loadJenisKelamin();
    loadTable();
    resetForm();

    txtIdPelanggan.setEditable(false);

    }
private boolean validasiInput() {

    if (txtNamaPelanggan.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Nama pelanggan wajib diisi!");

        txtNamaPelanggan.requestFocus();
        return false;
    }

    if (txtTelepon.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Nomor telepon wajib diisi!");

        txtTelepon.requestFocus();
        return false;
    }

    return true;
}

private void loadJenisKelamin() {

    cmbJenisKelamin.removeAllItems();

    cmbJenisKelamin.addItem("Laki-Laki");
    cmbJenisKelamin.addItem("Perempuan");
}
private void loadTable() {

   DefaultTableModel model = new DefaultTableModel(
    new Object[][]{},
    new String[]{
        "ID",
        "Nama Pelanggan",
        "Telepon",
        "Alamat",
        "Jenis Kelamin"
    }
){
    @Override
    public boolean isCellEditable(int row, int column){
        return false;
    }
};

    try {

        String sql = "SELECT * FROM pelanggan";

        Connection conn = Koneksi.getConnection();

        Statement st = conn.createStatement();

        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_pelanggan"),
                rs.getString("nama_pelanggan"),
                rs.getString("telepon"),
                rs.getString("alamat"),
                rs.getString("jenis_kelamin")
            });
        }

        tblPelanggan.setModel(model);
        tblPelanggan.setRowHeight(25);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Gagal memuat data : " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPelanggan = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        txtTelepon = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("ID Pelanggan");

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Telepon");

        jLabel6.setText("Alamat");

        txtIdPelanggan.addActionListener(this::txtIdPelangganActionPerformed);

        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        txtTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTeleponKeyTyped(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(102, 255, 102));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setBackground(new java.awt.Color(102, 255, 102));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        txtHapus.setBackground(new java.awt.Color(255, 102, 102));
        txtHapus.setText("Hapus");
        txtHapus.addActionListener(this::txtHapusActionPerformed);

        btnReset.setBackground(new java.awt.Color(255, 102, 102));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        jLabel7.setText("Cari Pelanggan");

        txtCari.addActionListener(this::txtCariActionPerformed);
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Data Pelanggan");

        tblPelanggan.setBackground(new java.awt.Color(255, 255, 102));
        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "Jenis Kelamin", "Telepon", "Alamat"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPelanggan);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pelanggan_24.png"))); // NOI18N
        jLabel1.setText("FORM PELANGGAN");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnKembali)
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelepon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(32, 32, 32)
                                .addComponent(btnEdit)
                                .addGap(92, 92, 92)
                                .addComponent(txtHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPelangganActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

     if (!validasiInput()) {
        return;
    }
    try {

        String sql = "INSERT INTO pelanggan "
                + "(nama_pelanggan, telepon, alamat, jenis_kelamin) "
                + "VALUES (?, ?, ?, ?)";

        Connection conn = Koneksi.getConnection();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1,
                txtNamaPelanggan.getText());

        pst.setString(2,
                txtTelepon.getText());

        pst.setString(3,
                txtAlamat.getText());

        pst.setString(4,
                cmbJenisKelamin.getSelectedItem().toString());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Data pelanggan berhasil disimpan");

        loadTable();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here
        if(txtIdPelanggan.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(this,
            "Pilih data yang akan diedit!");
    return;
}
        if (!validasiInput()) {
    return;
}
        
        try {

        String sql = "UPDATE pelanggan "
                + "SET nama_pelanggan=?, "
                + "telepon=?, "
                + "alamat=?, "
                + "jenis_kelamin=? "
                + "WHERE id_pelanggan=?";

        Connection conn = Koneksi.getConnection();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1, txtNamaPelanggan.getText());
        pst.setString(2, txtTelepon.getText());
        pst.setString(3, txtAlamat.getText());
        pst.setString(4,
                cmbJenisKelamin.getSelectedItem().toString());

        pst.setInt(5,
                Integer.parseInt(txtIdPelanggan.getText()));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Data pelanggan berhasil diubah");

        loadTable();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHapusActionPerformed
        // TODO add your handling code here:
        if(txtIdPelanggan.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(this,
            "Pilih data yang akan dihapus!");
    return;
}
        int konfirmasi =
        JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

if(konfirmasi != JOptionPane.YES_OPTION){
    return;
}
        try {

        String sql =
                "DELETE FROM pelanggan WHERE id_pelanggan=?";

        Connection conn = Koneksi.getConnection();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setInt(1,
                Integer.parseInt(txtIdPelanggan.getText()));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Data pelanggan berhasil dihapus");

        loadTable();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_txtHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
       
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        // TODO add your handling code here:
       int row = tblPelanggan.getSelectedRow();

    txtIdPelanggan.setText(
            tblPelanggan.getValueAt(row, 0).toString());

    txtNamaPelanggan.setText(
            tblPelanggan.getValueAt(row, 1).toString());

    txtTelepon.setText(
            tblPelanggan.getValueAt(row, 2).toString());

    txtAlamat.setText(
            tblPelanggan.getValueAt(row, 3).toString());

    cmbJenisKelamin.setSelectedItem(
            tblPelanggan.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblPelangganMouseClicked

    
    private void cariPelanggan() {

    DefaultTableModel model =
            new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Pelanggan");
    model.addColumn("Telepon");
    model.addColumn("Alamat");
    model.addColumn("Jenis Kelamin");

    try {

        String sql =
                "SELECT * FROM pelanggan "
                + "WHERE nama_pelanggan LIKE ?";

        Connection conn =
                Koneksi.getConnection();

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1,
                "%" + txtCari.getText() + "%");

        ResultSet rs =
                pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_pelanggan"),
                rs.getString("nama_pelanggan"),
                rs.getString("telepon"),
                rs.getString("alamat"),
                rs.getString("jenis_kelamin")
            });
        }

        tblPelanggan.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
}
    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
         if(txtCari.getText().trim().isEmpty()){
        loadTable();
        return;
    }

    cariPelanggan();
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtTeleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleponKeyTyped
        // TODO add your handling code here:
   char c = evt.getKeyChar();

if(!Character.isDigit(c)){
    evt.consume();
}

if(txtTelepon.getText().length() >= 15){
    evt.consume();
}
    }//GEN-LAST:event_txtTeleponKeyTyped

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new FrmDashboard().setVisible(true);
    dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPelanggan().setVisible(true));
    }
private void resetForm() {

    txtIdPelanggan.setText("");
    txtNamaPelanggan.setText("");
    txtTelepon.setText("");
    txtAlamat.setText("");
    txtCari.setText("");

    cmbJenisKelamin.setSelectedIndex(0);

    txtNamaPelanggan.requestFocus();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JButton txtHapus;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
