package view;
import config.Koneksi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FrmSupplier extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSupplier.class.getName());

    /**
     * Creates new form FrmSupplier
     */
    public FrmSupplier() {
       initComponents();
    loadTable();
    resetForm();
    txtIdSupplier.setEditable(false);
          
    }
    
   private void loadTable() {

    DefaultTableModel model = new DefaultTableModel(
        new Object[][]{},
        new String[]{
            "ID",
            "Nama Supplier",
            "Alamat",
            "Telepon"
        }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    try {

        String sql = "SELECT * FROM supplier";

        Connection conn = Koneksi.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_supplier"),
                rs.getString("nama_supplier"),
                rs.getString("alamat"),
                rs.getString("telepon")
            });
        }

        tblSupplier.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Gagal memuat data : " + e.getMessage());

    }
}
    private boolean validasiInput() {

    String nama = txtNamaSupplier.getText().trim();
    String telepon = txtTelepon.getText().trim();

    if (nama.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Nama supplier wajib diisi!");
        txtNamaSupplier.requestFocus();
        return false;
    }

    if (telepon.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Nomor telepon wajib diisi!");
        txtTelepon.requestFocus();
        return false;
    }

    if (!telepon.matches("[0-9]+")) {
        JOptionPane.showMessageDialog(this,
                "Nomor telepon hanya boleh angka!");
        txtTelepon.requestFocus();
        return false;
    }

    if (telepon.length() < 10) {
        JOptionPane.showMessageDialog(this,
                "Nomor telepon tidak valid!");
        txtTelepon.requestFocus();
        return false;
    }

    return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdSupplier = new javax.swing.JTextField();
        txtNamaSupplier = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Supplier Apotek");

        jLabel2.setText("ID Supplier");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("Telepon");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        jLabel6.setText("Cari Supplier");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Data Supplier");

        txtCari.addActionListener(this::txtCariActionPerformed);
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Supplier", "Nama", "Alamat", "Telepon"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdSupplier)
                    .addComponent(txtNamaSupplier)
                    .addComponent(txtAlamat)
                    .addComponent(txtTelepon)
                    .addComponent(txtCari)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(68, 68, 68)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btnHapus)
                        .addGap(61, 61, 61)
                        .addComponent(btnReset)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(257, 257, 257))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnReset)
                    .addComponent(btnHapus))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
         resetForm();
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     if (txtIdSupplier.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Pilih data yang akan dihapus!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus supplier ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi != JOptionPane.YES_OPTION) {
        return;
    }

    try {

       String sql =
        "DELETE FROM supplier WHERE id_supplier=?";

        Connection conn = Koneksi.getConnection();

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1,
                Integer.parseInt(txtIdSupplier.getText()));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Data supplier berhasil dihapus");

        loadTable();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Gagal menghapus data : " + e.getMessage());

    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
     
    if (!validasiInput()) {
        return;
    }

    try {

        String sql = """
    INSERT INTO supplier
    (nama_supplier, alamat, telepon)
    VALUES (?, ?, ?)
""";

        Connection conn = Koneksi.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql);

      pst.setString(1, txtNamaSupplier.getText().trim());
pst.setString(2, txtAlamat.getText().trim());
pst.setString(3, txtTelepon.getText().trim());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Data supplier berhasil disimpan");

        loadTable();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Gagal menyimpan data : " + e.getMessage());

    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         if (txtIdSupplier.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Pilih data yang akan diubah!");
        return;
    }

    if (!validasiInput()) {
        return;
    }

    try {

     String sql = """
    UPDATE supplier
    SET nama_supplier=?,
        alamat=?,
        telepon=?
    WHERE id_supplier=?
""";

        Connection conn = Koneksi.getConnection();

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtNamaSupplier.getText().trim());
        pst.setString(2, txtAlamat.getText().trim());
        pst.setString(3, txtTelepon.getText().trim());
        pst.setInt(4,
                Integer.parseInt(txtIdSupplier.getText()));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Data supplier berhasil diubah");

        loadTable();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Gagal mengubah data : " + e.getMessage());

    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
      int row = tblSupplier.getSelectedRow();

    txtIdSupplier.setText(
            tblSupplier.getValueAt(row, 0).toString());

    txtNamaSupplier.setText(
            tblSupplier.getValueAt(row, 1).toString());

    txtAlamat.setText(
            tblSupplier.getValueAt(row, 2).toString());

    txtTelepon.setText(
            tblSupplier.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
           DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Supplier");
    model.addColumn("Alamat");
    model.addColumn("Telepon");

    try {

      String sql = """
    SELECT *
    FROM supplier
    WHERE nama_supplier LIKE ?
       OR alamat LIKE ?
       OR telepon LIKE ?
""";

        Connection conn = Koneksi.getConnection();

        PreparedStatement pst = conn.prepareStatement(sql);

        String keyword = "%" + txtCari.getText().trim() + "%";

        pst.setString(1, keyword);
        pst.setString(2, keyword);
        pst.setString(3, keyword);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_supplier"),
                rs.getString("nama_supplier"),
                rs.getString("alamat"),
                rs.getString("telepon")
            });

        }

        tblSupplier.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Pencarian gagal : " + e.getMessage());

    }
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSupplier().setVisible(true));
    }
    
  private void resetForm() {

    txtIdSupplier.setText("");
    txtNamaSupplier.setText("");
    txtAlamat.setText("");
    txtTelepon.setText("");

    txtNamaSupplier.requestFocus();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdSupplier;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
